version: "3.9"

services:
  api:
    ports:
      - 8000:8000
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    restart: unless-stopped
    networks:
      - ehealth-backend-tier
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      - ./saleor/saleor/:/app/saleor:Z
      - ./saleor/templates/:/app/templates:Z
      - ./saleor/tests/:/app/tests
      # shared volume between worker and api for media
      - media-vol:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file: common.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - STOREFRONT_URL=http://localhost:3000/
      - DASHBOARD_URL=http://localhost:9000/

  storefront:
    build:
      context: ./saleor-storefront
      dockerfile: ./Dockerfile.prod
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./saleor-storefront/:/app:cached
      - /app/node_modules/
    command: npm start
    env_file: common.env

  dashboard:
    build:
      context: ./saleor-dashboard
      dockerfile: ./Dockerfile.prod
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - ./saleor-dashboard/:/app:cached
      - /app/node_modules/
    command: npm start -- --host 0.0.0.0
    env_file: common.env

  db:
    image: library/postgres:13.3-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - ehealth-backend-tier
    volumes:
      - db-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ehealth
      - POSTGRES_PASSWORD=ehealth

  redis:
    image: library/redis:6.2.4-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - ehealth-backend-tier
    volumes:
      - redis-vol:/data

  worker:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - ehealth-backend-tier
    env_file: common.env
    depends_on:
      - redis
      - mailhog
    volumes:
      - ./saleor/saleor/:/app/saleor:Z,cached
      - ./saleor/templates/:/app/templates:Z,cached
      # shared volume between worker and api for media
      - media-vol:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - ehealth-backend-tier

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - ehealth-backend-tier

volumes:
  db-vol:
    driver: local
  redis-vol:
    driver: local
  media-vol:

networks:
  ehealth-backend-tier:
    driver: bridge
